# Generated by Django 5.0.2 on 2024-05-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultoriaApp', '0002_chapter_cursos_delete_video_chapter_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='course_name',
            field=models.CharField(default='Nombre de Curso', max_length=100),
        ),
        migrations.AddField(
            model_name='cursos',
            name='video',
            field=models.FileField(default='ConsultoriaApp/24', upload_to='ConsultoriaApp/%y'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
